name: colorisationCNN_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - scikit-image
  - numpy
  - matplotlib
  - pillow
  - ipython
  - pip
  - pip:
    - argparse